services:
  frontend_app:
    build: ./frontend_app
    container_name: metiscare-frontend
    hostname: frontend-app-metiscare
    volumes: ['./frontend_app/src:/appcode']
    ports:
      - 3000:3000
    command: npm start

  backend_app:
    build: ./backend
    container_name: metiscare-backend
    hostname: backend-metiscare
    volumes: ['./backend:/backend-code']
    ports:
      - 4000:4000